import {useEffect,useState} from 'react'
import {AnimatePresence,m} from 'motion/react'
import {useWorkspace} from '../lib/store'
import {useMetrics} from '../lib/metrics'
import {request,loadMessages,report} from '../lib/rpc'
import {Button,Disclosure,Switch,usePrompt} from './UI'
import {RichMarkdown} from './RichMessage'
import {Icon} from './Icon'
const number=(value:number|null|undefined)=>value==null?'待更新':value.toLocaleString('zh-CN')
const money=(value:number|undefined)=>value==null?'待更新':`$${value.toFixed(4)}`
function Rows({rows}:{rows:[string,unknown][]}){return <dl className="metric-rows">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value==null?'未提供':String(value)}</dd></div>)}</dl>}
export function ContextBar(){
 const {stats,online}=useMetrics(),compaction=useWorkspace(s=>s.telemetry.compaction),state=useWorkspace(s=>s.state),usage=stats?.contextUsage
 return <div className="context-bar"><Button title="上下文与运行详情" onClick={()=>useWorkspace.getState().set({inspector:!useWorkspace.getState().inspector})}><Icon name="brain"/>Context {online?`${number(usage?.tokens)} / ${number(usage?.contextWindow??state?.model?.contextWindow)}`:'—'}{usage?.percent!=null&&` · ${usage.percent.toFixed(1)}%`}</Button><span>{compaction?.status==='running'?'正在压缩…':state?state.autoCompactionEnabled?'自动压缩开启':'自动压缩关闭':'自动压缩 —'}</span></div>
}
export function Inspector(){
 const cwd=useWorkspace(s=>s.cwd)
 const {stats,runtime,error,updatedAt,online}=useMetrics(),state=useWorkspace(s=>s.state),telemetry=useWorkspace(s=>s.telemetry),transcript=useWorkspace(s=>s.transcript)
 const ask=usePrompt(),[clock,setClock]=useState(()=>Date.now())
 useEffect(()=>{if(telemetry.compaction?.status!=='running')return;const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer)},[telemetry.compaction?.status])
 const usage=stats?.contextUsage,capacity=usage?.contextWindow??state?.model?.contextWindow,percent=usage?.percent
 const compaction=telemetry.compaction
 const attributedToolUsage=Object.entries(transcript.tools).filter(([,tool])=>tool.usage)
 async function compact(){const customInstructions=await ask({title:'压缩上下文',multiline:true});if(customInstructions!==null)await request({type:'compact',customInstructions},180000).then(()=>loadMessages(cwd))}
 return <aside className="inspector">
 <header><strong>运行详情</strong></header>
 <div className="inspector-scroll">
 <section><h3>上下文窗口</h3><div className="context-number">{number(usage?.tokens)}<small> / {number(capacity)} tokens</small></div><div className="context-meter" role="progressbar" aria-label="上下文使用量" aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent??undefined} aria-valuetext={percent==null?'压缩后等待下一次模型用量':`${percent.toFixed(1)}%`}><m.div className="context-meter-fill" animate={{scaleX:Math.min(1,Math.max(0,(percent??0)/100))}} initial={false} style={{transformOrigin:'left'}} transition={{duration:0.3}}/></div><p className="metric-note">{percent==null?'当前上下文用量待 Pi 更新':`已用 ${percent.toFixed(1)}% · 剩余 ${number(capacity!=null&&usage?.tokens!=null?Math.max(0,capacity-usage.tokens):null)}`}</p><Rows rows={[["模型最大输出",number(state?.model?.maxTokens)],["预留输出空间",runtime?number(runtime.compaction.reserveTokens):null],["压缩时保留近期",runtime?number(runtime.compaction.keepRecentTokens):null],["压缩阈值（上限减预留）",capacity&&runtime?number(Math.max(0,capacity-runtime.compaction.reserveTokens)):null]]}/></section>
 <section><h3>上下文压缩<Switch aria-label="自动压缩" checked={state?.autoCompactionEnabled??false} disabled={!online} onChange={enabled=>void request({type:'set_auto_compaction',enabled}).catch(report)}/></h3><AnimatePresence mode="wait">{compaction?<m.div key={compaction.startedAt} className={`compaction-status ${compaction.status}`} initial={{opacity:0}} animate={{opacity:1}}><strong>{{running:'正在压缩',complete:'压缩完成',cancelled:'已取消压缩',error:'压缩失败'}[compaction.status]}</strong><Rows rows={[["触发原因",{manual:'手动',threshold:'达到阈值',overflow:'上下文溢出'}[compaction.reason]??compaction.reason],["耗时",`${Math.max(0,((compaction.endedAt??clock)-compaction.startedAt)/1000).toFixed(1)} 秒`],["压缩前",compaction.tokensBefore==null?'未提供':number(compaction.tokensBefore)],["压缩后（估算）",compaction.estimatedTokensAfter==null?'未提供':number(compaction.estimatedTokensAfter)],["完成后重试",compaction.willRetry?'是':'否']]}/>{compaction.error&&<p className="error-inline">{compaction.error}</p>}{compaction.summary&&<Disclosure title="查看压缩摘要"><RichMarkdown text={compaction.summary}/></Disclosure>}{compaction.usage&&<Rows rows={[["压缩调用 tokens",number(compaction.usage.totalTokens)],["压缩调用费用",money(compaction.usage.cost?.total)]]}/>}</m.div>:<p className="metric-note">此连接期间还没有压缩事件。历史摘要可在会话树查看。</p>}</AnimatePresence><Button className="secondary" disabled={!online||transcript.running||transcript.compacting} onClick={()=>void compact().catch(report)}>立即压缩</Button></section>
 <section><h3>累计用量</h3><Rows rows={[["输入",number(stats?.tokens.input)],["输出",number(stats?.tokens.output)],["缓存读取",number(stats?.tokens.cacheRead)],["缓存写入",number(stats?.tokens.cacheWrite)],["总 tokens",number(stats?.tokens.total)],["费用估算",money(stats?.cost)]]}/><p className="metric-note">价格来自模型配置；中转站实际账单以服务商为准。</p></section>
 <section><h3>当前响应</h3><Rows rows={[["运行状态",transcript.phase],["本次输入",telemetry.usage?number(telemetry.usage.input):'未提供'],["本次输出",telemetry.usage?number(telemetry.usage.output):'未提供'],["本次缓存读/写",telemetry.usage?`${number(telemetry.usage.cacheRead)} / ${number(telemetry.usage.cacheWrite)}`:'未提供'],["本次总 tokens",telemetry.usage?number(telemetry.usage.totalTokens):'未提供']]}/></section>
 <section><h3>队列与工具</h3><Rows rows={[["待处理消息",state?.pendingMessageCount],["引导 / 跟进",`${transcript.queue.steering.length} / ${transcript.queue.followUp.length}`],["引导投递模式",state?.steeringMode],["跟进投递模式",state?.followUpMode],["执行中工具",Object.values(transcript.tools).reduce<string[]>((names,tool)=>{if(tool.running)names.push(tool.name);return names},[]).join(', ')||'无'],["累计工具调用",stats?.toolCalls],["累计工具结果",stats?.toolResults],["全部历史消息",stats?.totalMessages],["当前上下文消息",state?.messageCount],["用户 / 助手消息",stats?`${stats.userMessages} / ${stats.assistantMessages}`:null]]}/>{attributedToolUsage.length>0?<Rows rows={attributedToolUsage.map(([id,tool])=>[`${tool.name} · ${id.slice(0,6)}`,`${tool.usage?.totalTokens.toLocaleString()} tokens${tool.usage?.cost?.total!=null?` · $${tool.usage.cost.total.toFixed(4)}`:''}`])}/>:<p className="metric-note">Pi 的标准工具通常不返回独立 token 用量；可归因的嵌套模型用量会在工具卡中显示。</p>}</section>
 <section><h3>重试<Switch aria-label="自动重试" checked={runtime?.retry.enabled??false} disabled={!online} onChange={enabled=>void request({type:'set_auto_retry',enabled}).catch(report)}/></h3><Rows rows={[["状态",telemetry.retry?.status??'没有重试事件'],["当前 / 最大次数",telemetry.retry?`${telemetry.retry.attempt??'—'} / ${telemetry.retry.maxAttempts??runtime?.retry.maxRetries??'—'}`:null],["延迟",telemetry.retry?.delayMs==null?'未提供':`${telemetry.retry.delayMs} ms`],["配置最大重试",runtime?.retry.maxRetries],["基础延迟",runtime?`${runtime.retry.baseDelayMs} ms`:null]]}/>{telemetry.retry?.error&&<p className="error-inline">{telemetry.retry.error}</p>}<Button disabled={!online} onClick={()=>void request({type:'abort_retry'}).catch(report)}>终止重试</Button></section>
 <section><h3>模型与会话</h3><Rows rows={[["Provider",state?.model?.provider],["模型 ID",state?.model?.id],["API 协议",state?.model?.api],["Thinking",state?.thinkingLevel],["支持输入",state?.model?.input.join(', ')],["传输偏好",runtime?.transport],["项目信任",runtime?runtime.projectTrusted?'已信任':'未信任':null],["会话 ID",state?.sessionId],["会话文件",state?.sessionFile]]}/>{runtime?.thinkingBudgets&&<Disclosure title="思考预算配置"><pre>{JSON.stringify(runtime.thinkingBudgets,null,2)}</pre></Disclosure>}{runtime&&<Disclosure title="系统提示词"><pre>{runtime.systemPrompt}</pre></Disclosure>}</section>
 <section><h3>实时事件</h3><div className="event-log">{telemetry.events.map(event=><div key={`${event.at}-${event.type}-${event.detail??''}`}><time>{new Date(event.at).toLocaleTimeString()}</time><code>{event.type}</code>{event.detail&&<p>{event.detail}</p>}</div>)}</div></section>
 </div><footer>{error?`状态读取失败：${String(error)}`:updatedAt?`更新于 ${new Date(updatedAt).toLocaleTimeString()}`:'等待 Pi 数据'}</footer>
 </aside>
}
